name = "teralink"
main = "worker.js"
compatibility_date = "2025-12-10"
pages_build_output_dir = "."

# Worker 환경변수
[vars]
LOG_API_KEY = "110526taeyoon!"
JWT_SECRET = "y2OcX0sVflvpp5JE5UcoZc69VJyn9hXGXID8Igp145NBYT5gWKEfySukhLzmKsdrUocjXPYPO7SZXLLJbazgRA=="
ADMIN_PASSWORD_HASH = "3c0ef0d6e303d8d1a4e6b9d67841f20d17b366d74e9f3236c91a91680a4608ef"
ADMIN_TOTP_SECRET = "JBSWY3DPEHPK3PXP"
TURNSTILE_SECRET_KEY = "0x4AAAAAACGiuEYfvz-4LdWPdJBMESTP5cc"

# D1 Database 연결
[[d1_databases]]
binding = "LOG_DB"
database_name = "teralink_logs"
database_id = "94662c07-c04c-45ab-8e9e-f12582bd73b8"

[[d1_databases]]
binding = "teralink_db"
database_name = "teralink-db"
database_id = "4109bd29-f148-494b-9668-f9c9f26a3975"